// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoym0B2sOd0k-Whk4ezeFrjxgN5_VJA9M',
    appId: '1:1027671457053:web:34f92ff63aedfa9376f5f4',
    messagingSenderId: '1027671457053',
    projectId: 'fitness-24b08',
    authDomain: 'fitness-24b08.firebaseapp.com',
    storageBucket: 'fitness-24b08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvIX6hSnl75rupybaPBiZ6AjGlVUAy5bY',
    appId: '1:1027671457053:android:2d60f227322d418676f5f4',
    messagingSenderId: '1027671457053',
    projectId: 'fitness-24b08',
    storageBucket: 'fitness-24b08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6VRDlhXZ_DaeNlla4beycF7jsN3n_Cdk',
    appId: '1:1027671457053:ios:399dd24f673ca12d76f5f4',
    messagingSenderId: '1027671457053',
    projectId: 'fitness-24b08',
    storageBucket: 'fitness-24b08.appspot.com',
    iosClientId: '1027671457053-ttnnj4m16pqbcpsp15jc9f9rp2lvl4q3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6VRDlhXZ_DaeNlla4beycF7jsN3n_Cdk',
    appId: '1:1027671457053:ios:399dd24f673ca12d76f5f4',
    messagingSenderId: '1027671457053',
    projectId: 'fitness-24b08',
    storageBucket: 'fitness-24b08.appspot.com',
    iosClientId: '1027671457053-ttnnj4m16pqbcpsp15jc9f9rp2lvl4q3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );
}
