// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

// ...


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJAoySgAodjBKBfadqciJHdoiCVgIkxOg',
    appId: '1:296972320612:web:675f07cfdeee5797c78471',
    messagingSenderId: '296972320612',
    projectId: 'fitness-ff1b6',
    authDomain: 'fitness-ff1b6.firebaseapp.com',
    databaseURL: 'https://fitness-ff1b6-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-ff1b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwfOR4EDgc0M2CDakUTVD3kSB1zTniq5M',
    appId: '1:296972320612:android:ab4c16fffb3588fec78471',
    messagingSenderId: '296972320612',
    projectId: 'fitness-ff1b6',
    databaseURL: 'https://fitness-ff1b6-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-ff1b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH3LokJq5dPIPjaTVsl4Y6SgNQZBwcqoc',
    appId: '1:296972320612:ios:2e9c118e80d1775fc78471',
    messagingSenderId: '296972320612',
    projectId: 'fitness-ff1b6',
    databaseURL: 'https://fitness-ff1b6-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-ff1b6.appspot.com',
    iosClientId: '296972320612-tv4ae8aghtttalismier6u1pjd0lidgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH3LokJq5dPIPjaTVsl4Y6SgNQZBwcqoc',
    appId: '1:296972320612:ios:2e9c118e80d1775fc78471',
    messagingSenderId: '296972320612',
    projectId: 'fitness-ff1b6',
    databaseURL: 'https://fitness-ff1b6-default-rtdb.firebaseio.com',
    storageBucket: 'fitness-ff1b6.appspot.com',
    iosClientId: '296972320612-tv4ae8aghtttalismier6u1pjd0lidgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );
}
